# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/medtext',
                'doc_host': 'https://masapasa.github.io',
                'git_url': 'https://github.com/masapasa/medtext',
                'lib_path': 'medtext'},
  'syms': { 'medtext.core': { 'medtext.core.foo': ( 'https://masapasa.github.io/core.html#foo',
                                                    'https://github.com/masapasa/medtext/blob/master/medtext/core.py#L7')}}}